class ShotSmoke22 : actor { 
	Default {
		
		+NOTDMATCH;
		+NOINTERACTION;
		vspeed 1;
		renderstyle "Add";
		alpha 0.3;
		scale 0.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 Thing_ChangeTID(0,390);
			SMOK ABCDEFGHIJKLMNOPQ 1 A_SpawnItem("ShotSmokeTrail");//A_FadeOut(0.01)
			Stop;
	}
}

class ShotSmokeTrail : ShotSmoke22 { 
	Default {
		
		vspeed 0;
		alpha 0.15;
	}
	States
	{
		Spawn:
			SMOK CDEFGHIJKLMNOPQ 1;
			Stop;
	}
}

class SmokingPiece22 : DebrisGeneral { 
	Default {
		
		-NOGRAVITY;
		speed 12;
		gravity 0.7;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 Thing_ChangeTID(0,390);
			TNT1 A 1 A_SpawnItem("SmokingPiece22Smoke");
			wait;
	}
}

class SmokingPiece22Smoke : ShotSmokeTrail { 
	Default {
		
		scale 0.06;
		alpha 0.5;
	}
}

class BrutalExplosion : actor { 
	Default {
		
		+NOCLIP;
		+THRUactorS;
		+MISSILE;
		//WORKER // Надо ли?
		//RADIUS 16
		//HEIGHT 24
	}
	States
	{
		Spawn:
			MISL B 2 BRIGHT;
			MISL C 2 BRIGHT;
			MISL D 2 BRIGHT A_Explode();
			MISL A 0 A_NOBLOCKING();
			MISL A 0 A_FALL();
			MISL A 0 A_ALERTMONSTERS();
			MISL A 0 A_SpawnITEMEX ("DETECTFLOORCRATER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			MISL A 0 A_SpawnITEMEX ("DETECTCEILCRATER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			MISL A 0 A_SpawnITEMEX ("EXPLOSIONFLARESpawnER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			MISL A 0 A_SpawnITEMEX ("BARRELKABOOM",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			MISL AAAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONFLAMES", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 360));
			MISL AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONPARTICLEHEAVY", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 180));
			MISL AAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONPARTICLEHEAVY", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 180));
			MISL A 0 RADIUS_QUAKE (2, 24, 0, 15, 0);
			MISL A 0 Radius_Quake(3,15,0,5,0);
			MISL AA 0 A_CUSTOMMISSILE ("METALSHARD1", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			MISL AA 0 A_CUSTOMMISSILE ("METALSHARD2", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			MISL AA 0 A_CUSTOMMISSILE ("METALSHARD3", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			MISL A 0 A_PLAYSOUND("FAREXPL", 3);
			MISL A 0 A_SpawnITEM("BARRELEXPLOSIONSMOKECOLUMN");
			MISL AAAAAAA 0 A_custommissile("SmokingPiece22",random(0,16),random(-8,8),random(-360,360),2,random(10,70));
			MISL AAAAA 8 A_CUSTOMMISSILE ("EXPLOSIONSMOKE", 1, 0, RANDOM (0, 360), 2, RANDOM (50, 130));
			Stop;
	}
}

class DPTHQ_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel { 
	Default {
		
		//$Category Barrels
		DAMAGEFactor "TRAMPLE", 0.0;
		DAMAGEFactor "KICK", 0.1;
		DAMAGEFactor "MELEE", 0.1;
		DAMAGEFactor "FATALITY", 10.1;
		DAMAGEFactor "SUPERPUNCH", 10.1;
		DAMAGEFactor "EXPLOSIVEIMPACT", 0.4;
		DAMAGEFactor "FIRE", 3.5;
		DAMAGEFactor "BLOOD", 0.0;
		DAMAGEFactor "GREENBLOOD", 0.0;
		DAMAGEFactor "BLUEBLOOD", 0.0;
		DAMAGEFactor "TAUNT", 0.0;
		DAMAGEFactor "KILLME", 0.0;
		DAMAGEFactor "AVOID", 0.0;
		DAMAGEFactor "TAUNT", 0.0;
		DAMAGEFactor "HEAD", 0.0;
		DAMAGEFactor "MINORHEAD", 0.0;
		HEALTH 20;
		RADIUS 10;
		HEIGHT 34;
		MASS 200;
		DAMAGETYPE EXPLOSIVEIMPACT;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+NOICEDEATH;
		+PUSHABLE;
		+SLIDESONWALLS;
		+WINDTHRUST;
		+TELESTOMP;
		+NOBLOCKMONST;
		+FLOORCLIP;
		PAINCHANCE "KICK", 255;
		DEATHSOUND "EXPLOSION";
		OBITUARY "$OB_BARREL";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_CHECKSIGHT("Spawn2");
			BAR1 A 4  A_SpawnITEM("GREENLENSFLAREALTSMALL",0,32);
			TNT1 A 0 A_CHECKSIGHT("Spawn2");
			BAR1 A 4  A_SpawnITEM("GREENLENSFLAREALTSMALL",0,32);
			TNT1 A 0 A_CHECKSIGHT("Spawn2");
			BAR1 B 4  A_SpawnITEM("GREENLENSFLAREALTSMALL",0,32);
			TNT1 A 0 A_CHECKSIGHT("Spawn2");
			BAR1 B 4  A_SpawnITEM("GREENLENSFLAREALTSMALL",0,32);
			Loop;
		Spawn2:
			BAR1 A 2;
			Goto Spawn;
		PAIN.KICK:
			BAR1 A 1 A_PAIN();
			BAR1 A 1 A_FACETARGET();
			TNT1 A 0 THRUSTTHING(ANGLE*256/360+128, 20, 0, 0);
			TNT1 A 0 THRUSTTHINGZ(0,10,0,1);
			Goto Spawn;
		Death:
			BEXP AB 2 BRIGHT;
			BEXP C 2 A_Scream();
			BEXP D 2 A_Explode();
			BEXP A 0 A_NOBLOCKING();
			BEXP A 0 A_FALL();
			BEXP A 0 A_ALERTMONSTERS();
			BEXP A 0 A_SpawnITEMEX ("DETECTFLOORCRATER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BEXP A 0 A_SpawnITEMEX ("DETECTCEILCRATER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BEXP A 0 A_SpawnITEMEX ("EXPLOSIONFLARESpawnER",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BEXP A 0 A_SpawnITEMEX ("BARRELKABOOM",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BEXP AAAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONFLAMES", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 360));
			BEXP AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONPARTICLEHEAVY", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 180));
			BEXP AAAAAA 0 A_CUSTOMMISSILE ("EXPLOSIONPARTICLEHEAVY", 0, 0, RANDOM (0, 360), 2, RANDOM (0, 180));
			BEXP A 0 RADIUS_QUAKE (2, 24, 0, 15, 0);
			BEXP A 0 Radius_Quake(3,15,0,5,0);
			BEXP B 0 BRIGHT A_SCREAM();
			BEXP AA 0 A_CUSTOMMISSILE ("METALSHARD1", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			BEXP AA 0 A_CUSTOMMISSILE ("METALSHARD2", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			BEXP AA 0 A_CUSTOMMISSILE ("METALSHARD3", 5, 0, RANDOM (0, 360), 2, RANDOM (30, 160));
			BEXP A 0 A_PLAYSOUND("FAREXPL", 3);
			BEXP A 0 A_SpawnITEM("BARRELEXPLOSIONSMOKECOLUMN");
			BEXP AAAAAAA 0 A_custommissile("SmokingPiece22",random(0,16),random(-8,8),random(-360,360),2,random(10,70));
			BEXP AAAAAA 0 A_custommissile("BarrelPart",20,random(-5,5),random(0,360),2,random(40,80));
			BEXP A 0 A_SpawnItem("XBarrelChunk",0,0);
			BEXP AAAAA 8 A_CUSTOMMISSILE ("EXPLOSIONSMOKE", 1, 0, RANDOM (0, 360), 2, RANDOM (50, 130));
			BEXP EFGHIJKLMNOPQ 2;
			BEXP Q 1050 A_BarrelDestroy();
			BEXP Q 5 A_ReSpawn();
			Wait;
	}
}

class NuclearBarrel : DPTHQ_ExplosiveBarrel 16001 { 
	Default {
		
		//$Category Barrels
		damagefactor "Trample", 0.0;
		damagefactor "Kick", 0.1;
		damagefactor "Melee", 0.1;
		damagefactor "Fatality", 10.1;
		damagefactor "SuperPunch", 10.1;
		damagefactor "ExplosiveImpact", 0.4;
		damagefactor "Extremepunches", 0.0;
		damagefactor "Fire", 3.5;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "Head", 0.0;
		damagefactor "minorhead", 0.0;
		Health 3000;
		Radius 10;
		Height 34;
		Mass 200;
		DamageType ExplosiveImpact;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+NOICEDEATH;
		+PUSHABLE;
		+SLIDESONWALLS;
		+WINDTHRUST;
		+TELESTOMP;
		+NOBLOCKMONST;
		+FLOORCLIP;
		PainChance "Kick", 255;
		DeathSound "Explosion";
		Obituary "$OB_BARREL";
		Scale 0.75;
	}
	States
	{
		Spawn:
			NBAR B 6 a_playsound("DSDETECT",0,0.2,true,attn_static);
			Loop;
		Death:
			TNT1 A 1 A_Explode(2000, 500);
			BAR1 A 1 BRIGHT;
			BEXP ABCD 2 BRIGHT;
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_Fall();
			TNT1 DDDDDDDDDD 0 bright A_SpawnItemEx("explosionSpawner",0+Random(-20,20),0+Random(-20,20),32+Random(-5,5),0,0,1,0,128);
			TNT1 A 0;
			TNT1 A 0 A_PlaySoundEx("Nuke/Boom", "Voice", 0, 2);
			TNT1 A 0 Radius_Quake(54, 20, 70, 40, 0);
			TNT1 AA 0 A_SpawnItem("NukeHyperFlare", 0, 0, 0);
			TNT1 A 25 A_SpawnItem("NukeHyperFloor", 0, 0, 0);
			TNT1 AA 0 A_SpawnItem("NukeHyperSmokeFloor", 0, 0, 0);
			TNT1 A 0 A_SpawnItemEx("NukeHyperPillar", 0, 0, 0, 0, 0, 40, 0, 0, 0);
			TNT1 A 105 A_SpawnItemEx("NukeHyperSmokePillar", 0, 0, 0, 0, 0, 40, 0, 0, 0);
			TNT1 A 0 A_SpawnItem("NukeHyperMushroom", 0, 4000, 0);
			TNT1 AA 0 A_SpawnItem("NukeHyperSmokeMushroom", 0, 4000, 0);
			TNT1 AAAAAAAAAAAAA 0 A_CustomMissile("NukeNoclipper",3,0,random(0,360),2,random(0,360));
			TNT1 A 135;
			TNT1 AAAAAA 0 A_SpawnIteMEx("NukeRadiation1",random(2000,-2000),random(2000,-2000),random(0, 85));
			TNT1 AAAAAA 0 A_SpawnIteMEx("NukeRadiation2",random(2000,-2000),random(2000,-2000),random(0, 85));
			TNT1 AAAAAA 0 A_SpawnIteMEx("NukeRadiation3",random(2000,-2000),random(2000,-2000),random(0, 85));
			TNT1 AAAAAA 0 A_SpawnIteMEx("NukeRadiation4",random(2000,-2000),random(2000,-2000),random(0, 85));
			TNT1 A -1;
			TNT1 A 0 A_SpawnItemEx("Explosion", 0, 0, 0, 0, 0, 0, 0,SXF_NOCHECKPOSITION,0);// WORKER
			TNT1 A 5 A_NoBlocking();
			TNT1 A -1;
			Stop;
	}
}

class XBarrelChunk : actor { 
	Default {
		
	}
	States
	{
		Spawn:
			BEXP RSTRSTRSTRSTRSTRST 7 BRIGHT;
			BEXP RSTRST 8 BRIGHT;
			BEXP RSTRST 9 BRIGHT;
			BEXP RSTRSTRSTRRSSTTRRSSTTRRRSSSTTTRRRRSSSSTTTT 10;
			BEXP U -1;
			Stop;
	}
}

class BarrelPart : SmokingPiece22 { 
	Default {
		
		-ROCKETTRAIL;
		+DOOMBOUNCE;
		renderstyle "Translucent";
		alpha 1.0;
		scale 0.85;
		-NOBLOCKMAP;
		gravity 1.0;
		seesound "bounce";
		mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 Thing_ChangeTID(0,390);
			BPRT ABCDEFGH 2 A_SpawnItem("ShotSmoke");
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_jump(255,"death1","death2","death3","death4","death5","death6");
		Death1:
			BPRT A 1 A_Fadeout(0.001);
			Loop;
		Death2:
			BPRT C 1 A_Fadeout(0.001);
			Loop;
		Death3:
			BPRT E 1 A_Fadeout(0.001);
			Loop;
		Death4:
			BPRT G 1 A_Fadeout(0.001);
			Loop;
		Death5:
			BPRT B 1 A_Fadeout(0.001);
			Loop;
		Death6:
			BPRT D 1 A_Fadeout(0.001);
			Loop;
	}
}

class heliobj 29120 : actor { 
	Default {
		
		//$Category Military
		Health 2000;
		Radius 50;
		Height 70;
		Mass 10000;
		Damage 200;
		ExplosionDamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
	}
	States
	{
		Spawn:
			HELI A 1();
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}

class merda 16163 : actor { 
	Default {
		
		//$Category Amoral
		Radius 20;
		Height 4;
	}
	States
	{
		Spawn:
			MERD A -1;
			Loop;
	}
}

class Bodiless_Swarm 22930 : actor { 
	Default {
		
		+Missile;
		+NoBlockmap;
		+NoGravity;
		+NoSector;
		+Clientsideonly;
		Radius 1;
		Height 64;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySoundEX("SFX/Buzz","Body",1);
			TNT1 AAAAA 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
			TNT1 A -1;
			Stop;
	}
}

class Body_Swarm : actor { 
	Default {
		
		+Missile;
		+NoBlockmap;
		+NoGravity;
		+NoSector;
		+Clientsideonly;
		Radius 1;
		Height 64;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256,"Imp","Demon","ZombieMan","ShotgunGuy","CacoDemon","Player","GibbedPlayer");
			Loop;
		Imp:
			TNT1 A 0 A_SpawnItemEX("DeadDoomImp");
			Goto MakeSwarm;
		Demon:
			TNT1 A 0 A_SpawnItemEX("DeadDemon");
			Goto MakeSwarm;
		ZombieMan:
			TNT1 A 0 A_SpawnItemEX("DeadZombieMan");
			Goto MakeSwarm;
		ShotgunGuy:
			TNT1 A 0 A_SpawnItemEX("DeadShotgunGuy");
			Goto MakeSwarm;
		CacoDemon:
			TNT1 A 0 A_SpawnItemEX("DeadCacodemon");
			Goto MakeSwarm;
		Player:
			TNT1 A 0 A_SpawnItemEX("DeadMarine");
			Goto MakeSwarm;
		GibbedPlayer:
			TNT1 A 0 A_SpawnItemEX("GibbedMarine");
			Goto MakeSwarm;
		MakeSwarm:
			TNT1 A 0 A_PlaySoundEX("SFX/Buzz","Body",1);
			TNT1 AAAAA 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
			TNT1 A -1;
			Stop;
	}
}

class SwarmFly : actor { 
	Default {
		
		Radius 1;
		Height 1;
		Speed 5;
		PROJECTILE;
		+NOCLIP;
		ReactionTime 4;
		Scale 0.25;
	}
	States
	{
		Spawn:
		Spawn:
			SFLY A 1 ThrustThingZ(0, random (-1, 1), random (1, 0), 1)TNT1 A 0 A_ChangeVelocity(frandom(-2,2),frandom(-1,1),frandom(-2,2),1);
			SFLY B 1 ThrustThingZ(0, random (-1, 1), random (1, 0), 1)TNT1 A 0 A_ChangeVelocity(frandom(-1,1),frandom(-2,2),frandom(-1,1),1);
			SFLY A 0 A_CountDown();
			SFLY C 1 ThrustThingZ(0, random (-1, 1), random (1, 0), 1)TNT1 A 0 A_ChangeVelocity(frandom(-2,2),frandom(-1,1),frandom(-2,2),1);
			SFLY B 1 ThrustThingZ(0, random (-1, 1), random (1, 0), 1)TNT1 A 0 A_ChangeVelocity(frandom(-1,1),frandom(-2,2),frandom(-1,1),1);
			SFLY A 0 A_CountDown();
			Loop;
		Death:
			SFLY A 1 A_CustomMissile("SwarmFly",0,0,frandom(-20,20));
			Stop;
	}
}

class Mario64Tree 19202 : actor { 
	Default {
		
		//$Category Special
		Radius 8;
		Height 58;
		+SOLID;
		XScale 1;
		YScale 1.2;
	}
	States
	{
		Spawn:
			MTRE A 0;
			MTRE A 0 A_Jump(128,3);
			MTRE A 5;
			MTRE A -1;
			Stop;
			MTRE B 5;
			MTRE B -1;
			Stop;
	}
}
//**************** WEATHER ZONE BOUNDARY **********************
//Boundary object for weather zones
class WeatherSpot 30000 : actor { 
	Default {
		
		//$Category Weather
		+NOBLOCKMAP;
		gravity 0;
	}
	States
	{
		Spawn:
			TNT1 A -1;
			Loop;
	}
}
//**************** RAIN **********************
//Basic rain Spawner
class RainSpawner 26261 : actor { 
	Default {
		
		//$Category Weather
		+Missile;
		+NoClip;
		+NoGravity;
		+NoBlockMap;
		RenderStyle "Translucent";
		Alpha 0;
	}
	States
	{
		Spawn:
			RAIN A 0 A_JumpIf(z >= ceilingz,1);
			RAIN A 1 A_SpawnItemEx ("RainDrop", 0, 0, 0, random(0,1), random(0,1), -random(0,5), random(0,255), 0);
			Stop;
	}
}
//Heavy rain Spawner
class HardRainSpawner 26262 : actor { 
	Default {
		
		//$Category Weather
		+Missile;
		+NoClip;
		+NoGravity;
		+NoBlockMap;
		RenderStyle "Translucent";
		Alpha 0;
	}
	States
	{
		Spawn:
			RAIN A 0 A_JumpIf(z >= ceilingz,1);
			RAIN A 1 A_SpawnItemEx ("RainDrop", 0, 0, 0, random(0,1), random(0,1), -random(5,20), random(0,255), 0);
			Stop;
	}
}
//Simple rain drop
class RainDrop : actor { 
	Default {
		
		+NOBLOCKMAP;
		+DROPOFF;
		+MISSILE;
		+NOTELEPORT;
		+DontSplash;
		RenderStyle "Add";
		Alpha .5;
		xscale 0.25;
	}
	States
	{
		Spawn:
			RAIN A 1 A_JumpIf(waterlevel >= 1, "Death");
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
//**************** SNOW **********************
//Basic snow Spawner
class SnowSpawner 26264 : actor { 
	Default {
		
		//$Category Weather
		+Missile;
		+NoClip;
		+NoGravity;
		+NoBlockMap;
		RenderStyle "Translucent";
		Alpha 0;
	}
	States
	{
		Spawn:
			RAIN A 0 A_JumpIf(z >= ceilingz,1);
			RAIN A 1 A_SpawnItemEx ("SnowFlake", 0, 0, 0, random(0,5), random(0,5), -random(0,2), random(0,255), 0);
			Stop;
	}
}
//Hard snow Spawner
class HardSnowSpawner 26265 : actor { 
	Default {
		
		//$Category Weather
		+Missile;
		+NoClip;
		+NoGravity;
		+NoBlockMap;
		RenderStyle "Translucent";
		Alpha 0;
	}
	States
	{
		Spawn:
			RAIN A 0 A_JumpIf(z >= ceilingz,1);
			RAIN A 1 A_SpawnItemEx ("HeavySnowFlake", 0, 0, 0, random(0,3), random(0,3), -random(5,10), random(0,255), 0);
			Stop;
	}
}
//Light, drifting snow flake
class SnowFlake : actor { 
	Default {
		
		+NOBLOCKMAP;
		+DROPOFF;
		+MISSILE;
		+NOTELEPORT;
		+DontSplash;
		RenderStyle "Translucent";
		Alpha 0.9;
		gravity 0.02;
		scale 0.5;
	}
	States
	{
		Spawn:
			SNOW A 1 A_JumpIf(waterlevel >= 1, "Death");
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
//Heavy, wet snow flake
class HeavySnowFlake : actor { 
	Default {
		
		+NOBLOCKMAP;
		+DROPOFF;
		+MISSILE;
		+NOTELEPORT;
		+DontSplash;
		RenderStyle "Translucent";
		Alpha 0.9;
		gravity 0.1;
		scale 0.5;
	}
	States
	{
		Spawn:
			SNOW A 1 A_JumpIf(waterlevel >= 1, "Death");
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
//**************** CONTROL OBJECTS **********************
//Weather toggle effect
class Action_WeatherToggle : CustomInventory  { 
	Default {
		
		Inventory.Amount 1;
		Inventory.MaxAmount 1;
		-INVBAR;
		+UNDROPPABLE;
	}
	States 
	{ 
		Use:
			TNT1 A 0 A_JumpIfInventory("Flag_NoWeather",1,1);
			Goto StopEffects;
			TNT1 A 0 A_Print("Weather effects ON");
			TNT1 A 1 A_TakeInventory("Flag_NoWeather",999);
			TNT1 A 1 ACS_ExecuteAlways(941,0,0,0,0);
			Fail;
		StopEffects:
			TNT1 A 0 A_Print("Weather effects OFF");
			TNT1 A 1 A_GiveInventory("Flag_NoWeather",1);
			TNT1 A 1 ACS_ExecuteAlways(941,0,0,0,0);
			Fail;
	} 
}
class Flag_NoWeather : Inventory  { 
	Default {
		
		Inventory.Amount 1;
		Inventory.MaxAmount 1;
		-INVBAR;
	}
}
// Reviver
class Reviver 13377 : actor {
	Default {
	/*actor Reviver 13377
	 
		//$Category Special/
		speed 7
		PROJECTILE
		-FRIENDLY
		+NOGRAVITY
		+NOCLIP
	}
	States
	{
Spawn:
		TNT1 A 1 A_VileChase
		Loop
Death:
		TNT1 A 1
		STop
Heal:
		TNT1 A 1
		Stop
	}
}*/
// LOLNESS
class DANCE 10406 : actor { 
	Default {
		
		//$Category Dance
		Radius 10;
		Height 36;
		+SOLID;
		+PUSHABLE;
		+SHOOTABLE;
		scale 0.88;
	}
	States
	{
		Spawn:
			DANC DHEACGFBFGCAEH  2();
			Loop;
	}
}
class RUSSIA 10410 : actor { 
	Default {
		
		//$Category Dance
		Radius 10;
		Height 36;
		+SOLID;
		+PUSHABLE;
		+SHOOTABLE;
		scale 0.88;
	}
	States
	{
		Spawn:
			RUSS ABCDEFGHIJKLMNO  2();
			Loop;
	}
}
class FLEXIT 26370 : actor { 
	Default {
		
		//$Category Dance
		Radius 16;
		Height 16;
		+SOLID;
		+PUSHABLE;
		+SHOOTABLE;
		scale 0.88;
	}
	States
	{
		Spawn:
			PLYC ABCD 2;
			Loop;
	}
}
class REDC 21337 : actor { 
	Default {
		
		//$Category Special
		//PROJECTILE
		//-MISSILE
		-NOGRAVITY;
		Mass 99999;
	}
	States
	{
		Spawn:
			REDC A 7 A_SetTranslucent (0.25, 1);
			REDC A 7 A_SetTranslucent (0.75, 1);
			REDC A 7 A_SetTranslucent (1, 1);
			REDC A 7 A_SetTranslucent (0.75, 1);
			REDC A 7 A_SetTranslucent (0.25, 1);
			Loop;
	}
}
class TankBF 30037 : actor { 
	Default {
		
		//$Category Military
		Monster;
		Radius 80;
		Mass 1000000;
		height 80;
		+SOLID;
		+SHOOTABLE;
		+INVULNERABLE;
		+NOBLOOD;
		+NOPAIN;
		Speed 5;
		Health 1000;
	}
	States 
	{
		Spawn:
			TANK A 10 A_Look();
			Loop;
		See:
			TANK A 4 A_Chase();
			Loop;
		Missile:
			TANK B 10 A_FaceTarget();
			TANK B 8 A_CustomMissile("TankMissile", 95,0);
			TANK B 8;
			Goto See;
		Death:
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class TankMissile : Rocket { 
	Default {
		
		Scale 0.35;
		Radius 11;
		Height 8;
		Speed 20;
		Damage 20;
		Projectile;
		+RANDOMIZE;
		+DEHEXPLOSION;
		+ROCKETTRAIL;
		SeeSound "weapons/rocklf";
		DeathSound "weapons/rocklx";
	}
	States
	{
		Spawn:
			RPGR A 1 Bright;
			Loop;
		Death:
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Explosion : actor { 
	Default {
		
		Damage 255;
		explosiondamage 255;
		SeeSound "weapons/rocklx";
	}
	States
	{
		Spawn:
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class DIExplosion : Explosion { 
	Default {
		
		Scale 0.75;
	}
}
class DIExplosionLarge : Explosion { 
	Default {
		
		Scale 1.35;
	}
}
class Car1 21001 : actor { 
	Default {
		
		//$Category Cars
		Health 500;
		Radius 40;
		Height 56;
		Mass 2000000;
		Scale 0.5;
		Damage 200;
		explosiondamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
		DamageFactor "Melee", 0.05;
	}
	States
	{
		Spawn:
			CAMA A 1();
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Car2 21002 : actor { 
	Default {
		
		//$Category Cars
		Health 500;
		Radius 40;
		Height 56;
		Mass 2000000;
		Scale 0.9;
		Damage 200;
		explosiondamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
		DamageFactor "Melee", 0.05;
	}
	States
	{
		Spawn:
			GCAR A 1();
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Car3 21003 : actor { 
	Default {
		
		//$Category Cars
		Health 500;
		Radius 40;
		Height 56;
		Mass 2000000;
		Scale 1.2;
		Damage 200;
		explosiondamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
		DamageFactor "Melee", 0.05;
	}
	States
	{
		Spawn:
			FERR A 1();
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Car4 21004 : actor { 
	Default {
		
		//$Category Cars
		Health 500;
		Radius 40;
		Height 96;
		Mass 2000000;
		Scale 1;
		Damage 200;
		explosiondamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
		DamageFactor "Melee", 0.05;
	}
	States
	{
		Spawn:
			TRUK A 1;
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Car5 21005 : actor { 
	Default {
		
		//$Category Cars
		Health 500;
		Radius 40;
		Height 56;
		Mass 2000000;
		Scale 1.4;
		Damage 200;
		explosiondamage 200;
		DeathSound "weapons/rocklx";
		+SOLID;
		+NOBLOOD;
		+SHOOTABLE;
		+NOPAIN;
		DamageFactor "Melee", 0.05;
	}
	States
	{
		Spawn:
			PORS A 1();
			Loop;
		Death: 
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class Box1 12000 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 56;
		+SOLID;
	}
	States
	{
		Spawn:
			BOX1 A -1;
			Stop;
	}
}
class XboxOne 12001 : actor { 
	Default {
		
		//$Category Objects
		Radius 32;
		Height 64;
		+SOLID;
	}
	States
	{
		Spawn:
			XONE A -1;
			Stop;
	}
}
class PS4 12002 : actor { 
	Default {
		
		//$Category Objects
		Radius 32;
		Height 64;
		+SOLID;
	}
	States
	{
		Spawn:
			PS4B A -1;
			Stop;
	}
}
class Mine 20135 : actor { 
	Default {
		
		Damage 255;
		explosiondamage 255;
		DeathSound "weapons/rocklx";
		Radius 16;
		Mass 0x2fffffff;
		Height 16;
		Speed 0;
		Damage 1;
		Projectile;
		-FRIENDLY;
		MONSTER;
		-NOGRAVITY;
		+RANDOMIZE;
		+DEHEXPLOSION;
		SeeSound "claymone/peep";
		ActiveSound "claymone/peep";
		Obituary "%o can't seen this mines.";
	}
	States
	{
		Spawn:
			MINE A 1;
			Loop;
		Death:
			MINE B 10 A_PlaySound("MINE001");
			EXPL T 2 A_Explode();
			EXPL S 2 A_Scream();
			EXPL R 2 A_NoBlocking();
			EXPL Q 2;
			EXPL P 2;
			EXPL O 2;
			EXPL N 2;
			EXPL M 2;
			EXPL L 2;
			EXPL K 2;
			EXPL J 2;
			EXPL I 2;
			EXPL H 2;
			EXPL G 2;
			EXPL F 2;
			EXPL E 2;
			EXPL D 2;
			EXPL C 2;
			EXPL B 2;
			EXPL A 2;
			Stop;
	}
}
class DoomFlag : CustomInventory 14401  { 
	Default {
		
		//$Category Zone
		//-SOLID 
		Inventory.PickupSound "misc/k_pkup";
		Inventory.PickupMessage "You got the Doom flag!";
		Radius 20;
		Height 64;
	}
	States 
	{ 
		Spawn: 
			DFLG ABCDEF 3();
			Loop;
		Pickup: 
			TNT1 A 1 A_GiveInventory("DoomFlag1",1);
			Stop;
	} 
} 
class DoomFlag1 : CustomInventory  { 
	Default {
		
		radius 0;
		height 0;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
		Use:
			TNT1 A 1;
			fail;
	} 
}
class flaskblueA 26266 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS A -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskblueB 26267 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS G -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskpurpleA 26268 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS B -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskpurpleB 26269 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS H -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskredA 26270 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS C -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskredB 26271 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS I -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskgreenA 26272 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS D -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskgreenB 26273 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS J -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskyellowA 26274 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS E -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskyellowB 26275 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS K -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskgreyA 26276 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 7;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS F -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskgreyB 26277 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 6;
		Height 17;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			FLKS L -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class glassblue 26278 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK A -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
			Stop;
	}
}
class glasspurple 26279 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK B -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class glassred 26280 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK C -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class glassgreen 26281 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK D -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class glassyellow 26282 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK E -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class glassgrey 26283 : actor { 
	Default {
		
		//$Category Flasks
		mass 1500;
		Health 1;
		Radius 3;
		Height 8;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		RenderStyle "Translucent";
		DeathSound "tubes/break";
	}
	States
	{
		Spawn:
			BEAK F -1;
			Loop;
		Death:
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
			NULL A 0 A_Scream();
			Stop;
	}
}
class flaskshard1 26284 : actor { 
	Default {
		
		//$Category Flasks
		Radius 2;
		Height 4;
		speed 2;
		mass 1;
		RenderStyle "Translucent";
		Alpha 0.6;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+NOICEDEATH;
	}
	States
	{
		Spawn:
			TSR1 ABC 4;
			TSR1 D 4;
			TSR1 ABC 4;
			TSR1 D 4 A_Jump (24, "DeathA");
			TSR1 ABC 4;
			TSR1 D 4;
			TSR1 ABC 4;
			TSR1 D 4 A_Jump (24, "DeatB");
			Loop;
		DeathA:
			TSR1 C 5 A_Jump (80, "DeathA2");
			NULL A 1;
			Stop;
		DeathB:
			TSR1 D 5 A_Jump (80, "DeathB2");
			NULL A 1;
			Stop;
		DeathA2:
			TSR1 C 3 A_Jump (24, "DeathA2");
			NULL A 1;
			Stop;
		DeathB2:
			TSR1 D 5 A_Jump (24, "DeathB2");
			NULL A 1;
			Stop;
	}
}
class flaskshard2 26285 : actor { 
	Default {
		
		//$Category Flasks
		Radius 2;
		Height 4;
		speed 2;
		mass 1;
		RenderStyle "Translucent";
		Alpha 0.6;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+NOICEDEATH;
	}
	States
	{
		Spawn:
			TSR2 ADB 4;
			TSR2 C 4;
			TSR2 ADB 4;
			TSR2 C 4 A_Jump (24, "DeathA");
			TSR2 ADB 4;
			TSR2 C 4;
			TSR2 ADB 4;
			TSR2 C 4 A_Jump (24, "DeathB");
			Loop;
		DeathA:
			TSR2 C 5 A_Jump (80, "DeathA2");
			NULL A 1;
			Stop;
		DeathB:
			TSR2 D 5 A_Jump (80, "DeathB2");
			NULL A 1;
			Stop;
		DeathA2:
			TSR2 C 3 A_Jump (24, "DeathA2");
			NULL A 1;
			Stop;
		DeathB2:
			TSR2 D 5 A_Jump (24, "DeathB2");
			NULL A 1;
			Stop;
	}
}
class BlueKeyGizmo 6961 : actor { 
	Default {
		
		//$Category Special
		Radius 16;
		Height 44;
		+SOLID;
	}
	States
	{
		Spawn:
			DGIZ A 1;
			DGIZ A 1 A_SpawnItemEx("GizmoCard",0,0,60);
			DGIZ A 1 A_SpawnItemEx("BFS",0,0,64);
			DGIZ A 1 A_SpawnItemEx("BSparker",0,0,64);
			DGIZ A -1;
			Stop;
	}
}
class RedKeyGizmo 6962 : actor { 
	Default {
		
		//$Category Special
		Radius 16;
		Height 44;
		+SOLID;
	}
	States
	{
		Spawn:
			DGIZ A 1;
			DGIZ A 1 A_SpawnItemEx("GizmoCard",0,0,60);
			DGIZ A 1 A_SpawnItemEx("RFS",0,0,64);
			DGIZ A 1 A_SpawnItemEx("RSparker",0,0,64);
			DGIZ A -1;
			Stop;
	}
}
class YellowKeyGizmo 6963 : actor { 
	Default {
		
		//$Category Special
		Radius 16;
		Height 44;
		+SOLID;
	}
	States
	{
		Spawn:
			DGIZ A 1;
			DGIZ A 1 A_SpawnItemEx("GizmoCard",0,0,60);
			DGIZ A 1 A_SpawnItemEx("YFS",0,0,64);
			DGIZ A 1 A_SpawnItemEx("YSparker",0,0,64);
			DGIZ A -1;
			Stop;
	}
}
class GizmoCard : actor { 
	Default {
		
		Radius 16;
		Height 16;
		+SOLID;
		+NOGRAVITY;
		renderstyle "Add";
		alpha 0.9;
		Scale .5;
	}
	States
	{
		Spawn:
			GZKY A -1 Bright;
			Stop;
	}
}
class BFS : actor { 
	Default {
		
		+NOCLIP;
		+NOINTERACTION;
		+NOGRAVITY;
		renderstyle "Add";
		alpha 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZB A 3 Bright;
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZB B 3 Bright;
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZB C 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZB D 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class RFS : BFS { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZR A 3 Bright;
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZR B 3 Bright;
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZR C 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZR D 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class YFS: BFS { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZY A 3 Bright;
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZY B 3 Bright;
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZY C 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZY D 3 Bright;
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class BSparker: BFS { 
	Default {
		
		+FLOATBOB;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 AAAA 2;
			TNT1 A 0 A_Jump(8,"Zap");
			Loop;
		Zap:
			TNT1 A 0 A_Playsound("Zap");
			TNT1 A 1;
			TNT1 AAAA 0 A_SpawnItemEx("BSpark",random(-1,1),random(-1,1),0,random(-4,4),random(-4,4),random(2,5),0,143,0);
			Goto Spawn;
	}
}
class BSpark : actor { 
	Default {
		
		health 1;
		radius 8;
		height 1;
		mass 1;
		gravity 0.3;
		+CORPSE;
		+NOTELEPORT;
		+NOBLOCKMAP;
		-SOLID;
		Scale 0.125;
		renderstyle "Add";
		alpha 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZB A 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZB B 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZB C 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZB D 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class RSparker: BFS { 
	Default {
		
		+FLOATBOB;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 AAAA 2;
			TNT1 A 0 A_Jump(8,"Zap");
			Loop;
		Zap:
			TNT1 A 0 A_Playsound("Zap");
			TNT1 A 1;
			TNT1 AAAA 0 A_SpawnItemEx("RSpark",random(-1,1),random(-1,1),0,random(-4,4),random(-4,4),random(2,5),0,143,0);
			Goto Spawn;
	}
}
class RSpark : BSpark { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZR A 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZR B 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZR C 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZR D 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class YSparker: BFS { 
	Default {
		
		+FLOATBOB;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 A 0 A_Jump(128,4);
			TNT1 AAAA 2;
			TNT1 A 0 A_Jump(8,"Zap");
			Loop;
		Zap:
			TNT1 A 0 A_Playsound("Zap");
			TNT1 A 1;
			TNT1 AAAA 0 A_SpawnItemEx("YSpark",random(-1,1),random(-1,1),0,random(-4,4),random(-4,4),random(2,5),0,143,0);
			Goto Spawn;
	}
}
class YSpark : BSpark { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Jump(256,"A","B","C","D");
			Loop;
		A:
			GIZY A 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"B","C","D");
			Loop;
		B:
			GIZY B 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","C","D");
			Loop;
		C:
			GIZY C 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","D");
			Loop;
		D:
			GIZY D 3 Bright A_Fadeout(0.02);
			TNT1 A 0 A_Jump(256,"A","B","C");
			Loop;
	}
}
class Toilet1 290 : actor { 
	Default {
		
		//$Category Objects
		Tag "Toilet";
		Health 10;
		Radius 10;
		Height 34;
		Mass 10000000;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		+OLDRADIUSDMG;
		DeathSound "BREAK1";
	}
	States
	{
		Spawn:
			TOIL A 6;
			Loop;
		Death:
			TOIL A 1 A_Scream();
			TOIL B 4;
			TOIL C 2;
			TOIL D 2;
			TOIL E 2;
			TOIL F 3;
			Goto Water;
		Water:
			TOIF A 3 A_PlaySound ("TOILET1");
			TOIF B 3;
			TOIF C 3;
			TOIF D 3;
			TOIF A 3;
			TOIF B 3;
			TOIF C 3;
			TOIF D 3;
			TOIF A 3;
			TOIF B 3;
			TOIF C 3;
			TOIF D 3;
			TOIF A 3;
			TOIF B 3;
			TOIF C 3;
			TOIF D 3;
			Loop;
	}
}
class OilDrum 26286 : actor { 
	Default {
		
		//$Category Objects
		Health 20;
		Radius 10;
		Height 34;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+ACTIVATEMCROSS;
		+DONTGIB;
		+NOICEDEATH;
		+OLDRADIUSDMG;
		DeathSound "world/barrelx";
		Obituary "$OB_BARREL";
	}
	States
	{
		Spawn:
			OILD A 6;
			Loop;
		Death:
			OILD A 5 BRIGHT;
			OILD A 5 BRIGHT A_Scream();
			OILD B 5 BRIGHT;
			OILD C 5 BRIGHT A_Explode();
			OILC CCCCC 0 BRIGHT A_SpawnItemEx ("BarrelFlames", random (0, 40), random (0, 40), 0, 0, 0, 0, random (0, 360));
			OILD D 10 BRIGHT;
			OILD D 1050 BRIGHT A_BarrelDestroy();
			OILD D 5 A_ReSpawn();
			Wait;
	}
}
class BarrelFlames : actor { 
	Default {
		
		Radius 16;
		Height 24;
		ReactionTime 75;
		damagetype "fire";
		renderstyle "Add";
		Projectile;
		+NODAMAGETHRUST;
		+BLOODLESSIMPACT;
		-NOGRAVITY;
		-DROPOFF;
		-MISSILE;
		-ACTIVATEIMPACT;
		-ACTIVATEPCROSS;
	}
	States
	{
		Spawn:
			OILS A 0 bright;
			OILS A 4 bright A_PlaySoundEx ("BarrelFire/Loop", "SoundSlot5", 1);
			OILS A 0 bright A_PlaySoundEx ("BarrelFire/Start", "SoundSlot6");
			OILS BC 4 bright;
		FireLoop:
			OILF AB 4 bright;
			OILF C 4 bright A_Explode (5, 40);
			OILF C 0 bright A_CountDown();
			Loop;
		Death:
			OILS CB 4 bright;
			OILS A 4 bright A_StopSoundEx ("SoundSlot5");
			Stop;
	}
}
class TechBarrelGrey : ExplosiveBarrel 12711 { 
	Default {
		
		//$Category Objects
		DeathSound "TechBarrel/Explode";
		Obituary "%o ceased to exist.";
	}
	States
	{
		Spawn:
			BART A 6;
			Loop;
		Death:
			BARX A 4 bright A_Explode (128, 192);
			BARX A 0 bright A_Scream();
			BARX B 4 bright;
			BARX C 4 bright;
			BARX DEF 4 bright;
			TNT1 A 1054 A_BarrelDestroy();
			TNT1 A 5 A_ReSpawn();
			Wait;
	}
}
class TechBarrelTan : TechBarrelGrey 12712 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			BART B 6;
			Loop;
	}
}
class TechBarrelGreen : TechBarrelGrey 12713 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			BART C 6;
			Loop;
	}
}
class Zapper : SwitchableDecoration 26287 { 
	Default {
		
		//$Category Objects
		+SpawnCeiling;
		+NoGravity;
		+Solid;
		Radius 12;
		Height 32;
	}
	States
	{
		Spawn:
			ZAPR A 35;
			ZAPR A 0 A_Jump(64, "Active");
			Loop;
		Active:
			ZAPR B 0 A_PlaySoundEx("Zapper/Loop", "SoundSlot7", 1);
			ZAPR BCDEDCDEDCDEDCB 4 Bright;
			Zapr B 0 A_StopSoundEx("SoundSlot7");
			Goto Spawn;
		Inactive:
			ZAPR A -1;
			Loop;
	}
}
class Gardentree1 26288 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 20;
		Height 90;
		+Solid;
	}
	States
	{
		Spawn:
			PLAN A -1;
			Stop;
	}
}
class Gardentree2 26289 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 20;
		Height 90;
		+Solid;
	}
	States
	{
		Spawn:
			PLAN B -1;
			Stop;
	}
}
class Gardenbush1 26290 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 24;
		Height 30;
		+Solid;
	}
	States
	{
		Spawn:
			PLAN C -1;
			Stop;
	}
}
class Gardenbush2 26291 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 30;
		+Solid;
	}
	States
	{
		Spawn:
			PLAN D -1;
			Stop;
	}
}
class Gardenbush3 26292 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 30;
		+Solid;
	}
	States
	{
		Spawn:
			PLAN E -1;
			Stop;
	}
}
class NTreeDead1 26293 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 13;
		Height 160;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE A -1;
			Stop;
	}
}
class NTreeDead2 26294 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 13;
		Height 160;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE B -1;
			Stop;
	}
}
class NTreeSwamp1 26295 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 13;
		Height 140;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE C -1;
			Stop;
	}
}
class NTreeSwamp2 26296 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 10;
		Height 120;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE D -1;
			Stop;
	}
}
class NSwampLog 26297 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 12;
		Height 17;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE E -1;
			Stop;
	}
}
class NSwampStump 26298 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 12;
		Height 20;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE F -1;
			Stop;
	}
}
class NSwampRoot 26299 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 10;
		Height 20;
		+SOLID;
	}
	States
	{
		Spawn:
			NTRE G -1;
			Stop;
	}
}
////////////Green Holograms
class UACHolo1 26300 : actor { 
	Default {
		
		//$Category Objects
		Scale 0.5;
		Renderstyle "Add";
		+NOGRAVITY;
	}
	States
	{
		Spawn:
			UAC1 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
class UACHolo2 : UACHolo1 26301 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			UAC1 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Cyan Holograms
class UACHolo3 : UACHolo1 26302 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			UAC2 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner2", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
class UACHolo4 : UACHolo1 26303 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			UAC2 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner2", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Orange Holograms
class UACHolo5 : UACHolo1 26304 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			UAC3 A 2 BRIGHT A_SpawnItemEx("PlasmaSpawner3", random(-16,16), random(-16,16), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
class UACHolo6 : UACHolo1 26305 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			UAC3 B 2 BRIGHT A_SpawnItemEx("PlasmaSpawner3", random(-22,22), random(-22,22), random(-4,-12), 0, 0, random(6,8),0,SXF_NOCHECKPOSITION);
			Loop;
	}
}
////////////Plasma Particle Spawner
class PlasmaSpawner : actor { 
	Default {
		
		Alpha 0.75;
		RenderStyle "Add";
		+NOGRAVITY;
		+DONTSPLASH;
		+NOCLIP;
		-SOLID;
		Projectile;
	}
	States
	{
		Spawn:
			PLEM AAAAAAAAAAAAAAAA 1 BRIGHT A_FadeOut(0.09);
			Stop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
class PlasmaSpawner2 : plasmaSpawne {r////Cyan
	Default {
		
	}
	States
	{
		Spawn:
			PLEM BBBBBBBBBBBBBBBB 1 BRIGHT A_FadeOut(0.09);
			Stop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
class PlasmaSpawner3 : plasmaSpawne {r////Orange
	Default {
		
	}
	States
	{
		Spawn:
			PLEM CCCCCCCCCCCCCCCC 1 BRIGHT A_FadeOut(0.09);
			Stop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
class TankCreature 26306 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 70;
		+SOLID;
	}
	States
	{
		Spawn:
			CIAT ABCDEDCB 7;
			Loop;
	}
}
class TankNotCreature : TankCreature 26307 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			CIAT F -1;
			Loop;
	}
}
class TankBroken : TankCreature 26327 { 
	Default {
		
		//$Category Objects
	}
	States
	{
		Spawn:
			CIAT G -1;
			Loop;
	}
}
class SmallTree1 10700 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 96;
		+SOLID;
	}
	States
	{
		Spawn:
			TREN A -1;
			Stop;
	}
}
class SmallTree2 10701 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 64;
		+SOLID;
	}
	States
	{
		Spawn:
			TREN B -1;
			Stop;
	}
}
class SmallBush1 10702 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 24;
		+SOLID;
	}
	States
	{
		Spawn:
			BUSN A -1;
			Stop;
	}
}
class SmallBush2 10703 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 40;
		+SOLID;
	}
	States
	{
		Spawn:
			BUSN B -1;
			Stop;
	}
}
class SmallWinterTree1 10704 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 72;
		+SOLID;
	}
	States
	{
		Spawn:
			TRWN A -1;
			Stop;
	}
}
class SmallWinterTree2 10705 : actor { 
	Default {
		
		//$Category Vegetation
		Radius 16;
		Height 88;
		+SOLID;
	}
	States
	{
		Spawn:
			TRWN B -1;
			Stop;
	}
}
class soundbarrel 168 : actor { 
	Default {
		
		//$Category Objects
		radius 8;
		height 29;
		+solid;
	}
	States{
		Spawn:
			BARR ABCD 4;
			TNT1 A 0 a_playsound("radioactivebarrel/detected",0,0.2,true,attn_static);
loop}}
class emptybarrel 169 : actor { 
	Default {
		
		//$Category Objects
		radius 8;
		height 29;
		+solid;
	}
	States{
		Spawn:
			BARR E -1;
stop}}
class radioactivebarrel 170 : actor { 
	Default {
		
		//$Category Objects
		radius 8;
		height 29;
		+solid;
	}
	States{
		Spawn:
			BARR ABCD 4;
loop}}
class JunkPile1 26308 : actor { 
	Default {
		
		//$Category Objects
		Radius 25;
		Height 20;
		+SOLID;
	}
	States
	{
		Spawn:
			JPIL A -1;
			Stop;
	}
}
class JunkPile2 26309 : actor { 
	Default {
		
		//$Category Objects
		Radius 28;
		Height 28;
		+SOLID;
	}
	States
	{
		Spawn:
			JPIL B -1;
			Stop;
	}
}
class PlasmaGlobe 15500 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 48;
		+SOLID;
	}
	States
	{
		Spawn:
			PLOB ABCD 4 bright;
			Loop;
	}
}
class SeaMine 16004 : actor { 
	Default {
		
		//$Category Objects
		Health 20;
		Radius 24;
		Height 32;
		Scale 0.6;
		Mass 9001;
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+DONTGIB;
		+NOICEDEATH;
		+NOGRAVITY;
		+ISMONSTER;
		//  +TOUCHY
		DeathSound "world/barrelx";
		Obituary "%o was sunk.";
	}
	States
	{
		Spawn:
			SEAM E 0;
			SEAM E 1 A_SpawnItemEx ("MineChain", 0, 0, 0, 0, 0, -6, 0, SXF_SETMASTER, 0);
			//fall through
		Drift:
			SEAM E 6;
			Loop;
		Death:
			TNT1 A 1 A_RemoveChildren (1);
			TNT1 A 0 A_Scream();
			TNT1 A 0 A_Explode (64, 160);
			TNT1 A 0 A_SpawnItem ("SeaMineBoomFX", 0, 16);
			Stop;
	}
}
class SeaMineBoomFX : actor { 
	Default {
		
		Radius 2;
		Height 2;
		+NOINTERACTION;
	}
	States
	{
		Spawn:
			MISL B 8 Bright;
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}
class MineChain : actor { 
	Default {
		
		Radius 2;
		Height 2;
		Speed 6;
		Damage 0;
		Projectile;
	}
	States
	{
		Spawn:
			TNT1 A 1 A_SpawnItem ("MineChainLink");
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
class MineChainLink : actor { 
	Default {
		
		Radius 2;
		Height 2;
		+ISMONSTER;
		+NOGRAVITY;
	}
	States
	{
		Spawn:
			SCHN A 1;
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}
class Chair 26329 : actor { 
	Default {
		
		//$Category Objects
		+FloorClip;
		+Solid;
		Height 30;
		Radius 15;
	}
	States
	{
		Spawn:
			CHAI A -1;
			Stop;
	}
}
class HPipe1 325 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 128;
		Tag "Pipe 1";
		+SOLID;
	}
	States
	{
		Spawn:
			PIP1 A -1;
			Stop;
	}
}
class HPipe2 326 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 128;
		Tag "Pipe 2";
		+SOLID;
	}
	States
	{
		Spawn:
			PIP2 A -1;
			Stop;
	}
}
class HPipe3 327 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 128;
		Tag "Pipe 3";
		+SOLID;
	}
	States
	{
		Spawn:
			PIP3 A -1;
			Stop;
	}
}
class HPipe4 328 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 128;
		Tag "Pipe 4";
		+SOLID;
	}
	States
	{
		Spawn:
			PIP4 A -1;
			Stop;
	}
}
class HPipe5 329 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 128;
		Tag "Pipe 5";
		+SOLID;
	}
	States
	{
		Spawn:
			PIP5 A -1;
			Stop;
	}
}
//definition for the Czech Hedgehog tank-trap obstacle
//this object uses true-height, so the players and monsters CAN pass over it
class Hedgehog 26310 : actor { 
	Default {
		
		//$Title "Czech Hedgehog"
		//$Category Obstacles
		Radius 16;
		Height 40;
		+SOLID;
	}
	States
	{
		Spawn:
			HEDG A -1;
			Stop;
	}
}
class WasteBin 26311 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 24;
		Scale .5;
		+SOLID;
	}
	States
	{
		Spawn:
			WBIN A -1;
			Stop;
	}
}
class WasteBinFilthy 26328 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 24;
		Scale .5;
		+SOLID;
	}
	States
	{
		Spawn:
			WBIN B -1;
			Stop;
	}
}
class NecroBioBarrel : ExplosiveBarrel 16000 { 
	Default {
		
		//$Category Objects
		scale 0.75;
	}
	States
	{
		Spawn:
			NBAR A 6;
			Loop;
		Death:
			NBAR A 1();//A_SetScale (0.8, 0.75)
			NBAR A 1();//A_SetScale (0.85, 0.75)
			NBAR A 1();//A_SetScale (0.9, 0.75)
			NBAR A 1();//A_SetScale (0.95, 0.75)
			NBAR A 1();//A_SetScale (1, 0.75)
			TNT1 A 1 A_Scream();
			TNT1 A 0 A_SpawnItem ("NecroBarrelBoomFX", 0, 16);
			TNT1 A 9();
			TNT1 A 5 A_Explode();
			TNT1 A 1060 A_BarrelDestroy();
			TNT1 A 5 A_ReSpawn();
			Wait;
	}
}
class NecroAtomicBarrel : ExplosiveBarrel 16001 { 
	Default {
		
		//$Category Objects
		scale 0.75;
	}
	States
	{
		Spawn:
			NBAR B 6;
			Loop;
		Death:
			NBAR B 1();//A_SetScale (0.8, 0.75)
			NBAR B 1();//A_SetScale (0.85, 0.75)
			NBAR B 1();//A_SetScale (0.9, 0.75)
			NBAR B 1();//A_SetScale (0.95, 0.75)
			NBAR B 1();//A_SetScale (1, 0.75)
			TNT1 A 1 A_Scream();
			TNT1 A 0 A_SpawnItem ("NecroBarrelBoomFX", 0, 16);
			TNT1 A 9();
			TNT1 A 5 A_Explode();
			TNT1 A 1060 A_BarrelDestroy();
			TNT1 A 5 A_ReSpawn();
			Wait;
	}
}
class NecroBioBarrelPushable : NecroBioBarrel 16002 { 
	Default {
		
		//$Category Objects
		+PUSHABLE;
	}
}
class NecroAtomicBarrelPushable : NecroAtomicBarrel 16003 { 
	Default {
		
		//$Category Objects
		+PUSHABLE;
	}
}
class NecroBarrelBoomFX : actor { 
	Default {
		
		Radius 2;
		Height 2;
		+NOINTERACTION;
	}
	States
	{
		Spawn:
			MISL B 8 Bright;
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}
class HelmA 26312 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 10;
		+SOLID;
	}
	States
	{
		Spawn:
			AHLM A -1;
			Stop;
	}
}
class HelmB 26313 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 10;
		+SOLID;
	}
	States
	{
		Spawn:
			BHLM A -1;
			Stop;
	}
}
class HelmC 26314 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 10;
		+SOLID;
	}
	States
	{
		Spawn:
			CHLM A -1;
			Stop;
	}
}
class HelmD 26315 : actor { 
	Default {
		
		//$Category Objects
		Radius 6;
		Height 10;
		+SOLID;
	}
	States
	{
		Spawn:
			dHLM A -1;
			Stop;
	}
}
class Boots 26316 : actor { 
	Default {
		
		//$Category Objects
		Radius 8;
		Height 11;
		+SOLID;
	}
	States
	{
		Spawn:
			BOOT Z -1;
			Stop;
	}
}
class UniformA 26317 : actor { 
	Default {
		
		//$Category Objects
		Radius 12;
		Height 11;
		+SOLID;
	}
	States
	{
		Spawn:
			UNIF A -1;
			Stop;
	}
}
class UniformB 26318 : actor { 
	Default {
		
		//$Category Objects
		Radius 12;
		Height 11;
		+SOLID;
	}
	States
	{
		Spawn:
			UNIF B -1;
			Stop;
	}
}
//////////////////////////////
//////UMBRELLA////////////////SPRITE//SHADOW WARRIOR
//////////////////////////////
class Umbrella 26319 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 40;
		+SOLID;
	}
	States
	{
		Spawn:
			UMBR A -1;
			Stop;
	}
}
//////////////////////////////
/////TRASH CAN1///////////////SPRITE//DUKE NUKEM
//////////////////////////////
class TrashCan22 26320 : actor { 
	Default {
		
		//$Category Objects
		Radius 16;
		Height 40;
		+SOLID;
	}
	States
	{
		Spawn:
			TRAC Z -1;
			Stop;
	}
}
class TechLampOff : SwitchableDecoration 90 { 
	Default {
		
		//$Category Light
		Radius 16;
		Height 80;
		+SOLID;
		+USESPECIAL;
	}
	States
	{
		Active:
			TLMP A 0 A_PlaySound("switches/normbutn");
			// Fall through
		Lit:
			TLMP ABCD 4 Bright;//Light(BIGLAMP)
			Loop;
		Inactive:
			TLMP E 0 A_PlaySound("switches/exitbutn");
			// Fall through
		Spawn:
			TLMP E -1;
			Stop;
	}
}
class TechLampOn : TechLampOff 91 { 
	Default {
		
		//$Category Light
		//Activation THINGSPEC_Switch|THINGSPEC_Deactivate
	}
	States
	{
		Spawn:
	Goto Super::Lit
}
}
class EmptyNukageBarrel 26321 : actor { 
	Default {
	
	//$Category Objects
	+FloorClip;
	+Solid;
	Radius 12;
	Height 32;
	}
	States
	{
	Spawn:
		EBAR A -1;
		Stop;
}
}
class GreyMetalBarrel 26322 : actor { 
	Default {
	
	//$Category Objects
	+FloorClip;
	+Solid;
	Radius 12;
	Height 32;
	}
	States
	{
	Spawn:
		GBAR A -1;
		Stop;
}
}
class BrownMetalBarrel 26323 : actor { 
	Default {
	
	//$Category Objects
	+FloorClip;
	+Solid;
	Radius 12;
	Height 32;
	}
	States
	{
	Spawn:
		BBAR A -1;
		Stop;
}
}
class DoomDoll 26324 : actor { 
	Default {
	
	//$Category Objects
	Radius 28;
	Height 9;
	+SOLID;
	}
	States
	{
	Spawn:
		DDOL A -1;
		Stop;
}
}
class BrokenLamp 26325 : actor { 
	Default {
	
	//$Category Objects
	+FloorClip;
	+Solid;
	Height 30;
	Radius 10;
	}
	States
	{
	Spawn:
		BLMP A -1;
		Stop;
}
}

class TAMO 18668 : actor { 
	Default {
	
	//$Category Objects
	Tag "Tamamo No Mae";
	+FloorClip;
	+Solid;
	Height 30;
	Radius 10;
	}
	States
	{
	Spawn:
		TAMO A -1;
		Stop;
}
}

class OHRANA 18669 : actor { 
	Default {
	
	//$Category Objects
	Tag "Ohrana";
	+FloorClip;
	+Solid;
	Height 30;
	Radius 10;
	}
	States
	{
	Spawn:
		OHRN A -1;
		Stop;
}
}

class Bashkir 26403 : actor { 
	Default {
	
	//$Category Objects
	Tag "Bashkir";
	+FloorClip;
	+Solid;
	Height 30;
	Radius 10;
	}
	States
	{
	Spawn:
		KUTA K -1;
		Stop;
}
}

class TR3FB0 : BigTree 26258 { 
	Default {
	
	//$Category Vegetation
	}
	States
	{
	Spawn:
		TR3F B -1;
		Stop;
}
}

class TR3FS0 : TorchTree 26259 { 
	Default {
	
	//$Category Vegetation
	}
	States
	{
	Spawn:
		TR3F S -1;
		Stop;
}
}

class RoadCone 26357 : actor { 
	Default {
	
	Radius 8;
	Height 24;
	+SOLID;
	//$Category Objects
	}
	States
	{
	Spawn:
		VLCN A -1;
		Stop;
}
}

class "ZBOM_0" 26359 : actor { 
	Default {
	
	//$Category Objects
	Radius 24;
	Height 16;
	+SOLID;
	+PUSHABLE;
	}
	States
	{
	Spawn:
		ZBOM A 1 A_Jump(random(0,255), "Spawn2", "Spawn3", "Spawn4", "Spawn5", "Spawn6");
		Loop;
	Spawn2:
		ZBOM AB 25;
		Loop;
	Spawn3:
		ZBOM AB 20;
		Loop;
	Spawn4:
		ZBOM AB 15;
		Loop;
	Spawn5:
		ZBOM AB 10;
		Loop;
	Spawn6:
		ZBOM AB 5;
		Loop;
}
}

class DickColumn 26363 : actor { 
	Default {
	
	//$Category Objects
	Radius 16;
	Height 48;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		DICK A -1 Bright;
		Stop;
}
}
