//=================================================================================================
//
// Minigun
//
//=================================================================================================

class Minigun : weapon 5014 { 
	Default {
		
		
		Weapon.AmmoType "Clip";
		Weapon.AmmoGive 20;
		Weapon.AmmoUse 1;
		Weapon.Selectionorder 700;
		Weapon.Kickback 100;
		Inventory.PickupMessage "$PICKUP_MINIGUN";
		Obituary "$OB_MINIGUN";
		AttackSound "weapons/minigun";
		Radius 20;
		Height 16;
	}
	States
	{
		Spawn:
			MNGN A -1;
			Loop;
		Ready:
			MNGG A 1 A_WeaponReady();
			Loop;
		DeSelect:
			MNGG A 1 A_Lower();
			Loop;
		Select: 
			MNGG A 1 A_Raise();
			Loop;
		Fire: 
			MNGG A 0 A_GunFlash();
			MNGG A 2 A_FireBullets(5.6, 0, 1, 5, "BulletPuff");
			MNGG B 2 A_FireBullets(5.6, 0, 1, 5, "BulletPuff");
			MNGG A 2 A_ReFire();
			MNGG B 2;
			MNGG A 4;
			MNGG B 4;
			MNGG A 8;
			MNGG B 8;
			Goto Ready;
		Flash: 
			MNGF A 3 BRIGHT A_Light1();
			MNGF B 3 BRIGHT A_Light0();
			Stop;
	}
}

//=================================================================================================
//
// BFG10K
//
//=================================================================================================

class BFG10K : Doomweapon 5013 { 
	Default {
		
		
		Radius 20;
		Height 20;
		Weapon.Selectionorder 2800;
		Weapon.AmmoUse 5;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		Weapon.Kickback 100;
		Inventory.PickupMessage "$PICKUP_BFG10K";
		+WEAPON.NOAUTOFIRE;
		+WEAPON.NOLMS;
	}
	States
	{
		Spawn:
			BFG2 A -1;
			Stop;
		Ready:
			BG2G A 0 A_PlaySound ("weapons/bfg10kidle");
			BG2G A 1 A_WeaponReady();
			BG2G A 1 A_WeaponReady();
			BG2G A 1 A_WeaponReady();
			BG2G B 1 A_WeaponReady();
			BG2G B 1 A_WeaponReady();
			BG2G B 1 A_WeaponReady();
			BG2G C 1 A_WeaponReady();
			BG2G C 1 A_WeaponReady();
			BG2G C 1 A_WeaponReady();
			BG2G D 1 A_WeaponReady();
			BG2G D 1 A_WeaponReady();
			BG2G D 1 A_WeaponReady();
			Loop;
		DeSelect:
			BG2G E 1 A_Lower();
			Loop;
		Select:
			BG2G E 1 A_Raise();
			Loop;
		Fire:
			BG2G E 20 A_PlaySound ("weapons/bfg10kf");
			BG2G F 4;
			BG2G G 1;
			BG2G H 1;
			BG2G I 1;
			BG2G J 1;
			Goto Hold;
		Hold:
			BG2G K 2 A_GunFlash();
			BG2G L 2 A_FireBullets(0,0,1,0,"BFG10kShot");
			BG2G M 2;
			BG2G N 0 A_ReFire();
			BG2G O 35 A_PlaySound ("weapons/bfg10kcool");
			Goto Ready;
		Flash:
			TNT1 A 2 bright A_Light1();
			TNT1 A 3 bright;
			Goto LightDone;
			Stop;
	}
}

//=================================================================================================
//
// BFG10K explosive shot
//
//=================================================================================================

class BFG10kShot : actor { 
	Default {
		
		
		Radius 11;
		Height 8;
		Speed 20;
		Damage 160;
		DamageType BFG10k;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+ACTIVATEIMPACT;
		+ACTIVATEPCROSS;
		+NOTELEPORT;
		+PUFFONactorS;
		+PUFFGETSOWNER;
		+FORCERADIUSDMG;
		Renderstyle "Add";
		Alpha 0.75;
		SeeSound "weapons/bfg10kx";
		AttackSound "weapons/bfg10kx";
		Obituary "$OB_BFG10K";
	}
	States
	{
		Spawn:
			BFE1 A 0 bright;
			BFE1 A 3 bright A_Detonate();
			BFE1 BCDEF 3 bright;
			Stop;
	}
}

//=================================================================================================
//
// GrenadeLauncher
//
//=================================================================================================

class GrenadeLauncher : Doomweapon 5011 { 
	Default {
		
		
		Radius 20;
		Height 16;
		Weapon.Selectionorder 2500;
		+WEAPON.NOAUTOFIRE;
		+WEAPON.NOAUTOAIM;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 2;
		Weapon.AmmoType "Rocketammo";
		Weapon.Kickback 100;
		Inventory.PickupMessage "$PICKUP_GRENADELAUNCHER";
		
	}
	States
	{
		Spawn:
			GLAU A -1;
			Stop;
		Ready:
			GRLG A 1 A_WeaponReady();
			Loop;
		DeSelect:
			GRLG A 1 A_Lower();
			Loop;
		Select: 
			GRLG A 1 A_Raise();
			Loop;
		Fire: 
			GRLG B 8 A_GunFlash();
			GRLG B 12 A_FireCustomMissile ( "Grenade", 0, 1, 0, 0, 0, 6.328125 );
			GRLG B 0 A_ReFire();
			Goto Ready;
		Flash: 
			GRLF A3 bright A_Light1();
			GRLF B4 bright;
			GRLF C 4 bright A_Light2();
			GRLF D 4 bright A_Light2();
			Goto LightDone;
	}
}
