//=================================================================================================
//
// Hissy
//
//=================================================================================================

CLASS Hissy 5057 : ACTOR { 
	Default {
		
		//Game Doom
		Radius 20;
		Height 26;
		+SOLID;
	}
	States
	{
		Spawn:
			HISY B 1();//A_FaceConsolePlayer(5)
			wait;
			HISY A 1();//A_FaceConsolePlayer(5)
			Wait;
	}
}
